version: "3.5"

services:
  node:
    build: .
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - "8080:8080"
    networks:
      - dbn

networks:
  dbn:
    external:
      name: dbn